version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_react_hono_kanban_board
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_react_hono_kanban_board
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
